# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_auto_20171112_0745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermessage',
            options={'verbose_name': '用户留言信息', 'verbose_name_plural': '用户留言信息'},
        ),
        migrations.RenameField(
            model_name='usermessage',
            old_name='object_key',
            new_name='object_id',
        ),
    ]
